In [97]:
'''
Testing different ways of recommending movies
This was not used in final product
'''
import numpy as np
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd 
users = pd.read_csv("users.csv", sep=";")
users

ratings1 = pd.read_csv("ratings.csv")
movies = pd.read_csv("movies.csv")
ratings = pd.merge(movies, ratings1, on = 'movieId')
information = pd.merge(ratings, users, on='userId')


fem_under18 = information.loc[(information.Occupation == 'writer')&(information.rating >= 3.5)&(information.Age == '35-44')]

# count rows per `movie_id`
#abs_num_f_5s_ratings = f_5s_ratings.groupby("Movie_id").size()

top_movies = fem_under18.groupby("movieId").size()
top_movies
#Merge the two data sets on movieID
top_movies

movie_data = pd.merge(ratings1, movies, on='movieId')  
movie_data.groupby('title')['rating'].mean().sort_values(ascending=False)
ratings_mean_count = pd.DataFrame(movie_data.groupby('title')['rating'].mean())  

ratings_mean_count['rating_counts'] = pd.DataFrame(movie_data.groupby('title')['rating'].count())  

fem_under18

fem_avg_rating = pd.DataFrame(fem_under18.groupby('title')['rating'].mean())
#Get count of ammount of votes per movie and add to DF
fem_avg_rating['count_ratings'] = fem_under18.groupby('title')['rating'].count()
#avg_rating

top_ten_rated = fem_avg_rating.sort_values('rating', ascending=False).head(10)
ten_most_voted = fem_avg_rating.sort_values('count_ratings', ascending=False).head(10)


hundred_most_voted = fem_avg_rating.sort_values('count_ratings', ascending=False).head(50)
top_10 = hundred_most_voted.sort_values('rating', ascending=False).head(10)

top_10

                                                      rating  count_ratings
title
There Will Be Blood (2007)                          4.833333              3
Dr. Strangelove or: How I Learned to Stop Worry...  4.833333              3
Godfather, The (1972)                               4.750000              4
Lord of the Rings: The Fellowship of the Ring, ...  4.750000              4
Fight Club (1999)                                   4.700000              5
Silence of the Lambs, The (1991)                    4.687500              8
Slumdog Millionaire (2008)                          4.666667              3
Groundhog Day (1993)                                4.666667              3
WALL·E (2008)                                       4.666667              3
Seven (a.k.a. Se7en) (1995)                         4.600000              5