In [1]:
'''
Recommending movies based on movies that users similar to 
them like. 
'''
import pandas as pd 
import numpy as np

from collections import Counter
import warnings
warnings.filterwarnings('ignore')

ratings = pd.read_csv("ratings.csv")
movies = pd.read_csv("movies.csv")
ratings = pd.merge(ratings, movies, on='movieId')

#get the average rating for each movie and add to DF avg_rating
avg_rating = pd.DataFrame(ratings.groupby('movieId')['rating'].mean())
#Get count of ammount of votes per movie and add to DF
avg_rating['count_ratings'] = ratings.groupby('movieId')['rating'].count()

#this is something that will work in future when there are users that have voted on movies
#can only show it working based on current user data i have acquired

def similar_user(user):
    #merge ratings and movies
    ratings = pd.read_csv("ratings.csv")
    movies = pd.read_csv("movies.csv")
    ratings = pd.merge(ratings, movies, on='movieId')
    ratings_matrix = ratings.pivot_table(index='title', columns='userId', values='rating')
    user_id = ratings_matrix[user]
    similar_to=ratings_matrix.corrwith(user_id)
    correlation = pd.DataFrame(similar_to, columns=['Correlation'])
    correlation.dropna(inplace=True)
    correlation = correlation.join(avg_rating['count_ratings'])
    similar_movies = correlation[correlation['count_ratings'] > 1].sort_values(by='Correlation', ascending=False).head(5)
    return similar_movies

def users_faves(user):
    ratings = pd.read_csv("ratings.csv")
    user_demo = ratings.loc[(ratings.userId == user)].sort_values(by=['rating'], ascending=False).head(15)
    #return 5 most similar users based on ratings
    return user_demo

def get_movies(user):
    sim = similar_user(user)
    sim = sim.iloc[:,0:0]

    all_movies = []
    for col in sim.iterrows():
        all_movies.append(users_faves(col[0]))

    top_movies = []
    
    user1 =all_movies[0]
    top_movies.extend(user1['movieId'].values.tolist())
    user2 = all_movies[1]
    top_movies.extend(user2['movieId'].values.tolist())
    user3 = all_movies[2]
    top_movies.extend(user3['movieId'].values.tolist())
    user4 = all_movies[3]
    top_movies.extend(user4['movieId'].values.tolist())
    user5 = all_movies[4]
    top_movies.extend(user5['movieId'].values.tolist())

    return top_movies
    
user1_rec = get_movies(1001)
df_rec = pd.DataFrame(data= { 'movieId':user1_rec})

all_mov= [word for word, word_count in Counter(user1_rec).most_common(20)]
a = Counter(user1_rec).most_common(20)
b = pd.DataFrame(all_mov)
b.columns = ['movieId']
b= pd.merge(b, movies, on='movieId')
b

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,79132,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
2,162414,Moonlight,Drama
3,1573,Face/Off (1997),Action|Crime|Drama|Thriller
4,89745,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX
5,122904,Deadpool (2016),Action|Adventure|Comedy|Sci-Fi
6,59315,Iron Man (2008),Action|Adventure|Sci-Fi
7,109487,Interstellar (2014),Sci-Fi|IMAX
8,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller
9,68954,Up (2009),Adventure|Animation|Children|Drama
10,116797,The Imitation Game (2014),Drama|Thriller|War
11,115713,Ex Machina (2015),Drama|Sci-Fi|Thriller
12,112852,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
13,318,"Shawshank Redemption, The (1994)",Crime|Drama
14,102125,Iron Man 3 (2013),Action|Sci-Fi|Thriller|IMAX
15,134130,The Martian (2015),Adventure|Drama|Sci-Fi
16,122892,Avengers: Age of Ultron (2015),Action|Adventure|Sci-Fi
17,122882,Mad Max: Fury Road (2015),Action|Adventure|Sci-Fi|Thriller
18,1193,One Flew Over the Cuckoo's Nest (1975),Drama
19,3567,Bossa Nova (2000),Comedy|Drama|Romance